language: cpp
env:
  global:
  - secure: J32ES3Z/8YVm3tukNdTGyZ8/MdFhU8udkW23l4TsVRLRP95wcIb3HiwwTHCLKXsvDbTj2dOCU91gYbfjWLH7yynf8hpp1nVYbOCqHf3KYFn6cALSGnJATE9nRuwlcvW4Y9A5JooHOq/iSfuF/9eBsWobEkH9BPrmmjrupyoD7z0=
script: ./test/ci.sh
after_success:
- make javadoc
- .utility/push-javadoc-to-gh-pages.sh
